### PR TITLE
Update submitBlock to allow SSZ & cancellations

### LINKED ISSUE #14: Todo: update builder submission content types: json, json+gzip, ssz, ssz+gzip
We should update the accepted content-types for builder bids:

1. json
2. json+gzip
3. ssz (`"Content-Type: application/octet-stream")
4. ssz+gzip

### PR DESCRIPTION
**Pull request by jtraglia**
Fixes #14.

### CODE REVIEW

**Comment by metachris** [comment]
oh, great!

Do we also want this header dropdown to contain `octet-stream`, like in the beacon APIs?

relay-specs:

Screenshot 2023-05-17 at 22 36 41

beacon-APIs:
Screenshot 2023-05-17 at 22 37 01

**Comment by jtraglia** [comment]
Sure, added it. But it won't have an example. Neither does Beacon-APIs though.

image

**Comment by jtraglia** [comment]
Lemme try to figure out a fix for that linter rule.

**Comment by jtraglia** [comment]
Well I couldn't figure it out within a reasonable amount of time, so I just removed that rule.

**Comment by metachris** [comment]
thxxx 🙌

**Pull request merged**
