### PR TITLE
Update SubmitBlockRequest for Capella

### PR DESCRIPTION
**Pull request by jtraglia**
* Fix typo in readme.
* Update beacon-api repo so Capella types are available.
* For `SubmitBlockRequest` allow a Bellatrix or Capella execution payload.

For some reason the example isn't rendering what I would expect. Not sure how to fix it.

### CODE REVIEW

**Comment by metachris** [comment]
lgtm, let's merge?

**Comment by jtraglia** [comment]
> lgtm, let's merge?

Maybe, but there's still the issue in the example, it doesn't show a payload with `oneOf`.

image

@lightclient do you know how to fix this?

**Comment by metachris** [comment]
undraft?

**Comment by jtraglia** [comment]
> undraft?

Marked as ready for review. Not ideal, but we'll fix it later.

**Pull request merged**
